name: Run Preprocessing Dataset

on:
  push:
    branches: [ main ]

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas numpy Sastrawi scikit-learn nltk

      - name: Verify nltk installation
        run: |
          python -c "import nltk; print('✅ NLTK installed, version:', nltk.__version__)"

      - name: Run automate preprocessing script
        run: |
          echo "🚀 Starting automate preprocessing script..."
          python - <<'EOF'
          import nltk
          for pkg in ["punkt", "stopwords"]:
              try:
                  nltk.data.find(f"tokenizers/{pkg}" if pkg=="punkt" else f"corpora/{pkg}")
              except LookupError:
                  nltk.download(pkg, quiet=True)
          import os
          os.system("python preprocessing/automate_Eka-Fanya-Yohana-Dasilva.py")
          print("✅ Preprocessing completed successfully!")
          EOF

      - name: Upload processed dataset
        uses: actions/upload-artifact@v4
        with:
          name: processed-dataset
          path: preprocessing/namadataset_preprocessing/wisata_bali_preprocessed.csv
