name: Run Preprocessing Dataset

on:
  push:
    branches: [ main ]

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy Sastrawi scikit-learn nltk

      - name: Run automate script
        run: |
          python -m pip show nltk
          python preprocessing/automate_Eka-Fanya-Yohana-Dasilva.py

      - name: Upload processed dataset as artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-dataset
          path: preprocessing/namadataset_preprocessing/wisata_bali_preprocessed.csv
